services:
  - type: web
    name: forgejo-git-service
    env: docker
    repo: https://github.com/greatautomate/forge
    dockerfilePath: ./Dockerfile
    plan: starter
    region: virginia
    envVars:
      - key: APP_NAME
        value: "DotBypasser Git"
      - key: RUN_MODE
        value: "prod"
      - key: DB_TYPE
        value: "postgres"
      - key: ROOT_URL
        generateValue: true
      - key: SSH_DOMAIN
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: INTERNAL_TOKEN
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: forgejo-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: forgejo-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: forgejo-db
          property: user
      - key: DB_PASSWD
        fromDatabase:
          name: forgejo-db
          property: password
    disk:
      name: forgejo-data
      mountPath: /data
      sizeGB: 20
    healthCheckPath: /

databases:
  - name: forgejo-db
    databaseName: forgejo
    user: forgejo
    region: virginia
    # Note: Omitting 'plan' uses the default paid PostgreSQL plan
